spring:
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    cache-enabled: false